// Product seed data for the Kartly catalog.
//
// Brands are invented. Using real brand names in a demo storefront raises the
// same trademark problem as copying a real logo, and plausible fictional brands
// read just as convincingly.
//
// Tuple shape: { t: title, b: brand, p: price in cents, q: image query,
//                bl: bullets, sp: specs, v?: variants }
// Everything derivable (rating, review count, deal, stock, delivery, badges) is
// generated deterministically from the product id in generate-catalog.mjs, so
// the catalog is stable across rebuilds.

export const CATEGORIES = [
  { id: "electronics", name: "Electronics", blurb: "Audio, video and everyday tech", q: "consumer electronics" },
  { id: "computers", name: "Computers", blurb: "Laptops, desktops and accessories", q: "laptop computer" },
  { id: "home-kitchen", name: "Home & Kitchen", blurb: "Cookware, appliances and decor", q: "kitchen cookware" },
  { id: "fashion", name: "Clothing & Accessories", blurb: "Everyday essentials and outerwear", q: "clothing apparel" },
  { id: "sports", name: "Sports & Outdoors", blurb: "Training, camping and recovery", q: "outdoor camping gear" },
  { id: "beauty", name: "Beauty & Personal Care", blurb: "Skincare, haircare and grooming", q: "cosmetics skincare" },
  { id: "toys", name: "Toys & Games", blurb: "Building sets, board games and puzzles", q: "toys children" },
  { id: "books", name: "Books", blurb: "Fiction, reference and design", q: "stack of books" },
  { id: "office", name: "Office Products", blurb: "Desks, chairs and stationery", q: "office desk supplies" },
  { id: "pets", name: "Pet Supplies", blurb: "Beds, bowls and enrichment", q: "pet dog supplies" },
];

export const SEEDS = {
  electronics: [
    { t: 'Aureon Halo Pro Wireless Over-Ear Headphones, 40H Battery, Hybrid Active Noise Cancelling, Bluetooth 5.3, Memory Foam Earcups, Multipoint Pairing - Midnight Black', b: 'Aureon', p: 24999, q: 'headphones',
      bl: ['Hybrid ANC with four beamforming mics cuts cabin and office noise', 'Up to 40 hours playback, plus 5 hours from a 10-minute fast charge', 'Multipoint pairing keeps a laptop and phone connected at once', 'Memory foam earcups and a 248g frame stay comfortable all day'],
      sp: { Brand: 'Aureon', 'Model Name': 'Halo Pro', 'Form Factor': 'Over-Ear', Connectivity: 'Wireless, Bluetooth 5.3', 'Battery Life': '40 hours', Weight: '248 g' },
      v: [{ type: 'color', label: 'Midnight Black', swatch: '#1b1b1f' }, { type: 'color', label: 'Fog Grey', swatch: '#b9bbc0' }, { type: 'color', label: 'Sandstone', swatch: '#d9c6a8' }] },
    { t: 'Vantra Pulse 2 True Wireless Earbuds with Wireless Charging Case, Adaptive ANC, IPX5 Sweat Resistant, 32H Total Playtime', b: 'Vantra', p: 8999, q: 'wireless earbuds',
      bl: ['Adaptive ANC adjusts to your surroundings in real time', '8 hours per charge and 32 hours total with the pocketable case', 'IPX5 rated to shrug off sweat and rain during workouts', 'Tap controls for playback, calls and voice assistant'],
      sp: { Brand: 'Vantra', 'Model Name': 'Pulse 2', 'Form Factor': 'In-Ear', 'Water Resistance': 'IPX5', 'Battery Life': '32 hours total' },
      v: [{ type: 'color', label: 'White', swatch: '#f4f4f4' }, { type: 'color', label: 'Graphite', swatch: '#3a3a3c' }] },
    { t: 'Nordvik Field 4K Action Camera, 60FPS HDR Video, 6-Axis Stabilisation, Waterproof to 10m Without Housing, Dual Screen, 2 Batteries', b: 'Nordvik', p: 17900, q: 'action camera',
      bl: ['4K60 HDR capture with 6-axis electronic stabilisation', 'Waterproof to 10 metres with no external housing needed', 'Front and rear screens make framing yourself simple', 'Ships with two batteries and a magnetic quick-release mount'],
      sp: { Brand: 'Nordvik', 'Max Resolution': '4K 60fps', Stabilisation: '6-axis EIS', Waterproof: '10 m', Screens: 'Dual colour' } },
    { t: 'Lumea Arc 27" QHD Monitor, 165Hz, 1ms IPS, HDR400, 99% sRGB, USB-C 65W Power Delivery, Height Adjustable Stand', b: 'Lumea', p: 28900, q: 'computer monitor',
      bl: ['165Hz IPS panel with 1ms response for gaming and editing', 'Single USB-C cable carries video and 65W laptop charging', '99% sRGB coverage, factory calibrated out of the box', 'Tilt, swivel, pivot and 130mm height adjustment'],
      sp: { Brand: 'Lumea', 'Screen Size': '27 Inches', Resolution: '2560 x 1440', 'Refresh Rate': '165 Hz', 'Panel Type': 'IPS' } },
    { t: 'Kestrel Bloom Smart Speaker with Room-Filling 360° Sound, Voice Assistant, Multi-Room Audio, Fabric Finish', b: 'Kestrel', p: 7499, q: 'bluetooth speaker',
      bl: ['360° driver array fills a room from any position', 'Group with other Kestrel speakers for multi-room playback', 'Far-field mics hear you over music with a mute switch', 'Recycled fabric wrap in three colourways'],
      sp: { Brand: 'Kestrel', 'Speaker Type': 'Smart Speaker', Connectivity: 'Wi-Fi, Bluetooth', Power: 'Mains' },
      v: [{ type: 'color', label: 'Charcoal', swatch: '#4a4a4f' }, { type: 'color', label: 'Chalk', swatch: '#ece7df' }, { type: 'color', label: 'Moss', swatch: '#6c7a5d' }] },
    { t: 'Orvan Shift Portable Bluetooth Speaker, 24H Battery, IP67 Waterproof and Dustproof, Deep Bass Radiator, Carabiner Strap', b: 'Orvan', p: 5499, q: 'portable speaker',
      bl: ['24 hours of playback from a single charge', 'IP67 sealed against dust and full immersion', 'Passive bass radiator adds low end without the bulk', 'Braided strap and carabiner clip to a pack or bar'],
      sp: { Brand: 'Orvan', 'Battery Life': '24 hours', 'Water Resistance': 'IP67', Weight: '560 g' } },
    { t: 'Aureon Drift Wireless Charging Stand, 15W Fast Charge, Qi2 Magnetic Alignment, Adjustable Viewing Angle, USB-C Cable Included', b: 'Aureon', p: 3499, q: 'wireless charger',
      bl: ['Qi2 magnets snap the phone into perfect alignment', '15W fast charging for compatible handsets', 'Tilts between 15° and 65° for desk or bedside use', 'Non-slip base and a braided 1.5m USB-C cable'],
      sp: { Brand: 'Aureon', Output: '15 W', Standard: 'Qi2', Connector: 'USB-C' } },
    { t: 'Brightwell Nest Indoor Security Camera, 2K Resolution, Colour Night Vision, Two-Way Talk, Local SD Storage, No Subscription Required', b: 'Brightwell', p: 4999, q: 'security camera',
      bl: ['2K sensor with colour night vision down to 0.1 lux', 'Records to a local SD card with no monthly fee', 'Two-way talk and a privacy shutter you can see', 'Person and pet detection handled on-device'],
      sp: { Brand: 'Brightwell', Resolution: '2K', Storage: 'microSD up to 256GB', Power: 'USB-C mains' } },
    { t: 'Vantra Loop Fitness Tracker with Heart Rate and SpO2, 14-Day Battery, Sleep Staging, 120 Workout Modes, 5ATM Water Resistant', b: 'Vantra', p: 6499, q: 'fitness tracker',
      bl: ['14-day battery so charging is a fortnightly job', 'Continuous heart rate, SpO2 and sleep staging', '120 workout modes with automatic run detection', '5ATM rated for pool swimming'],
      sp: { Brand: 'Vantra', 'Battery Life': '14 days', 'Water Resistance': '5 ATM', Display: '1.47" AMOLED' },
      v: [{ type: 'color', label: 'Black', swatch: '#26262a' }, { type: 'color', label: 'Rose', swatch: '#e2b7b0' }, { type: 'color', label: 'Slate Blue', swatch: '#5a6b85' }] },
    { t: 'Meridia Type-C 100W Braided Cable 3-Pack, 2m Nylon Jacket, 480Mbps Data, E-Marker Chip, Laptop and Phone Compatible', b: 'Meridia', p: 1899, q: 'usb cable',
      bl: ['100W E-marked for laptops, tablets and phones', 'Double-braided nylon rated to 30,000 bends', 'Three 2-metre cables in one pack', 'Reinforced strain relief at both ends'],
      sp: { Brand: 'Meridia', Length: '2 m', Power: '100 W', 'Data Rate': '480 Mbps' } },
    { t: 'Nordvik Compact 65W GaN Wall Charger, 3 Ports, Foldable Pins, Laptop Fast Charge, Universal Compatibility', b: 'Nordvik', p: 3299, q: 'phone charger',
      bl: ['65W GaN in a body smaller than a matchbox', 'Two USB-C and one USB-A port charge three devices', 'Foldable pins make it genuinely pocketable', 'Intelligent power sharing across connected devices'],
      sp: { Brand: 'Nordvik', Output: '65 W', Ports: '2x USB-C, 1x USB-A', Technology: 'GaN III' } },
    { t: 'Lumea Glow Smart LED Light Strip 5m, 16 Million Colours, Music Sync, App and Voice Control, Adhesive Backing', b: 'Lumea', p: 2799, q: 'led lights',
      bl: ['16 million colours with segment-addressable zones', 'Music sync reacts to the room, not just the app', 'Cut to length every 10cm without losing function', '3M adhesive backing holds on painted walls'],
      sp: { Brand: 'Lumea', Length: '5 m', Control: 'App, Voice', Power: 'USB-C adapter' } },
  ],

  computers: [
    { t: 'Meridia Stratus 14 Laptop, Intel Core Ultra 7, 16GB LPDDR5X RAM, 1TB NVMe SSD, 14" 2.8K OLED 120Hz, Backlit Keyboard, Windows 11 Pro', b: 'Meridia', p: 119900, q: 'laptop computer',
      bl: ['Core Ultra 7 with a dedicated NPU for on-device AI work', '14" 2.8K OLED at 120Hz, 100% DCI-P3, factory calibrated', '16GB LPDDR5X and a 1TB Gen4 NVMe drive as standard', '1.29kg chassis with 18-hour rated battery life'],
      sp: { Brand: 'Meridia', Processor: 'Intel Core Ultra 7', RAM: '16 GB LPDDR5X', Storage: '1 TB NVMe SSD', Display: '14" 2.8K OLED 120Hz', OS: 'Windows 11 Pro', Weight: '1.29 kg' },
      v: [{ type: 'color', label: 'Space Grey', swatch: '#6e7276' }, { type: 'color', label: 'Platinum', swatch: '#d7d9db' }] },
    { t: 'Kestrel Forge 16 Gaming Laptop, 16" QHD+ 240Hz, 32GB DDR5, 2TB SSD, RTX Graphics, Vapour Chamber Cooling, RGB Per-Key Keyboard', b: 'Kestrel', p: 189900, q: 'gaming laptop',
      bl: ['16" QHD+ 240Hz panel with G-Sync support', '32GB DDR5 and 2TB of Gen4 storage, both upgradeable', 'Vapour chamber and dual fans hold clocks under load', 'Per-key RGB with onboard macro profiles'],
      sp: { Brand: 'Kestrel', Processor: 'Octa-core', RAM: '32 GB DDR5', Storage: '2 TB NVMe SSD', Display: '16" QHD+ 240Hz', OS: 'Windows 11 Home' } },
    { t: 'Orvan Mesa Mini Desktop PC, 8-Core CPU, 16GB RAM, 512GB SSD, Dual 4K Output, Wi-Fi 6E, VESA Mount Included', b: 'Orvan', p: 54900, q: 'desktop computer',
      bl: ['Drives two 4K displays from a 0.6 litre chassis', 'Wi-Fi 6E and 2.5Gb Ethernet built in', 'VESA bracket hides it behind any monitor', 'Tool-free access to RAM and storage'],
      sp: { Brand: 'Orvan', Processor: '8-Core', RAM: '16 GB DDR5', Storage: '512 GB NVMe SSD', Ports: 'HDMI 2.1, DP 1.4, 4x USB' } },
    { t: 'Aureon Tactile 87 Mechanical Keyboard, Hot-Swappable Switches, Gasket Mount, PBT Double-Shot Keycaps, USB-C, White Backlight', b: 'Aureon', p: 12900, q: 'mechanical keyboard',
      bl: ['Hot-swap sockets take any 3- or 5-pin switch', 'Gasket mount with foam damping for a softer bottom-out', 'PBT double-shot caps that will not go shiny', 'Detachable USB-C and full QMK-style remapping'],
      sp: { Brand: 'Aureon', Layout: '87-key TKL', Switches: 'Hot-swappable linear', Keycaps: 'PBT double-shot', Connection: 'USB-C detachable' },
      v: [{ type: 'color', label: 'White', swatch: '#f0f0ef' }, { type: 'color', label: 'Black', swatch: '#232326' }, { type: 'color', label: 'Navy', swatch: '#2f3f5c' }] },
    { t: 'Vantra Glide Wireless Ergonomic Mouse, 8000 DPI Sensor, Silent Clicks, USB-C Rechargeable, 6 Programmable Buttons, Multi-Device', b: 'Vantra', p: 4299, q: 'computer mouse',
      bl: ['Sculpted shape keeps the wrist at a neutral angle', 'Silent switches rated to 10 million clicks', 'Pairs with three devices and switches with one button', '70 days per charge, 3 hours from a 2-minute top-up'],
      sp: { Brand: 'Vantra', DPI: '8000', Buttons: '6 programmable', Connection: 'Bluetooth + 2.4GHz', Battery: 'USB-C rechargeable' } },
    { t: 'Brightwell Vertex 11-in-1 USB-C Docking Station, Dual 4K HDMI, 100W Pass-Through, Gigabit Ethernet, SD and microSD Readers', b: 'Brightwell', p: 8900, q: 'usb hub',
      bl: ['Eleven ports from a single USB-C connection', 'Dual 4K60 HDMI output for a two-monitor desk', '100W pass-through keeps the laptop charging', 'Aluminium shell doubles as a heatsink'],
      sp: { Brand: 'Brightwell', Ports: '11', Video: 'Dual 4K 60Hz HDMI', 'Power Delivery': '100 W', Ethernet: 'Gigabit' } },
    { t: 'Nordvik Vault 2TB Portable SSD, USB 3.2 Gen 2, 1050MB/s Read, Shock Resistant Aluminium Body, Hardware Encryption', b: 'Nordvik', p: 15900, q: 'external hard drive',
      bl: ['1050MB/s reads move a 50GB project in under a minute', 'Milled aluminium body rated for a 2-metre drop', '256-bit hardware encryption with no software needed', 'Works with Windows, macOS, iPad and Android'],
      sp: { Brand: 'Nordvik', Capacity: '2 TB', Interface: 'USB 3.2 Gen 2', 'Read Speed': '1050 MB/s', Encryption: 'AES-256 hardware' },
      v: [{ type: 'size', label: '1TB', priceDelta: -6000 }, { type: 'size', label: '2TB', priceDelta: 0 }, { type: 'size', label: '4TB', priceDelta: 14000 }] },
    { t: 'Lumea Clarity 4K Webcam with Sony Sensor, Auto Framing, Dual Noise-Cancelling Mics, Privacy Shutter, Tripod Thread', b: 'Lumea', p: 9900, q: 'webcam',
      bl: ['4K30 or 1080p60 through a Sony STARVIS sensor', 'Auto framing keeps you centred as you move', 'Two beamforming mics with onboard noise suppression', 'Mechanical shutter plus a standard tripod thread'],
      sp: { Brand: 'Lumea', Resolution: '4K 30fps', 'Field of View': '78°', Mount: 'Clip + 1/4" thread' } },
    { t: 'Kestrel Rise Aluminium Laptop Stand, Adjustable Height and Angle, Fits 10-17" Devices, Ventilated, Foldable for Travel', b: 'Kestrel', p: 3999, q: 'laptop stand',
      bl: ['Lifts the screen to eye level to spare your neck', 'Open frame lets hot air escape from the underside', 'Silicone pads grip the chassis without scratching', 'Folds flat enough for a laptop sleeve'],
      sp: { Brand: 'Kestrel', Material: 'Aluminium alloy', Compatibility: '10-17 inch', 'Max Load': '8 kg' } },
    { t: 'Orvan Quietframe 32GB DDR5 Desktop Memory Kit, 2x16GB, 6000MHz CL30, Aluminium Heatspreader, Intel XMP and AMD EXPO', b: 'Orvan', p: 11900, q: 'computer memory',
      bl: ['6000MHz CL30 tuned for both XMP and EXPO', 'Low-profile heatspreader clears tall air coolers', 'Hand-binned dies with a lifetime warranty', 'Matched pair tested together before shipping'],
      sp: { Brand: 'Orvan', Capacity: '32 GB (2x16GB)', Speed: '6000 MHz', Latency: 'CL30', Type: 'DDR5 DIMM' } },
    { t: 'Meridia Beam Monitor Light Bar, Asymmetric Glare-Free LED, Auto Brightness, Wireless Remote, No Screen Reflection, USB Powered', b: 'Meridia', p: 5900, q: 'desk lamp',
      bl: ['Asymmetric optics light the desk, never the screen', 'Ambient sensor matches brightness to the room', 'Rotary remote for brightness and colour temperature', 'Counterweighted clip fits flat and curved monitors'],
      sp: { Brand: 'Meridia', 'Colour Temperature': '2700K-6500K', Power: 'USB-C 5V', Length: '45 cm' } },
    { t: 'Brightwell Anchor Under-Desk Cable Management Tray, Steel, No-Drill Clamp Fit, 2 Sizes Included, Holds Power Strips and Adapters', b: 'Brightwell', p: 3299, q: 'cable management',
      bl: ['Clamps on with no drilling into the desktop', 'Powder-coated steel holds 5kg of bricks and strips', 'Two tray widths in the box for different desks', 'Open mesh keeps adapters from overheating'],
      sp: { Brand: 'Brightwell', Material: 'Powder-coated steel', 'Max Load': '5 kg', Installation: 'Clamp, no drilling' } },
  ],

  "home-kitchen": [
    { t: 'Nordvik Chef 10-Piece Stainless Steel Cookware Set, Tri-Ply Clad, Induction Compatible, Oven Safe to 260°C, Tempered Glass Lids', b: 'Nordvik', p: 24900, q: 'cookware set',
      bl: ['Tri-ply construction heats evenly right up the walls', 'Works on every hob including induction', 'Oven and grill safe to 260°C with the lids on', 'Riveted stay-cool handles and a lifetime warranty'],
      sp: { Brand: 'Nordvik', Material: 'Tri-ply stainless steel', Pieces: '10', 'Oven Safe': '260 °C', Induction: 'Yes' } },
    { t: 'Lumea Barista Espresso Machine, 20 Bar Italian Pump, Built-In Conical Burr Grinder, Steam Wand, PID Temperature Control', b: 'Lumea', p: 44900, q: 'espresso machine',
      bl: ['Conical burr grinder with 30 settings built in', 'PID control holds brew temperature within 1°C', 'Commercial steam wand for proper microfoam', 'Pre-infusion pass makes shots far more forgiving'],
      sp: { Brand: 'Lumea', Pressure: '20 bar', Grinder: 'Conical burr, 30 settings', 'Water Tank': '2.5 L', Power: '1450 W' } },
    { t: 'Kestrel Everyday 6.5L Air Fryer, Dual Basket, Sync Finish, Digital Touch Display, Dishwasher Safe Non-Stick Trays, 9 Presets', b: 'Kestrel', p: 13900, q: 'air fryer',
      bl: ['Two independent baskets cook different foods at once', 'Sync Finish lands both dishes at the same moment', 'Nine presets from chips to whole roast chicken', 'Trays and baskets go straight in the dishwasher'],
      sp: { Brand: 'Kestrel', Capacity: '6.5 L total', Baskets: '2', 'Temperature Range': '40-200 °C', Power: '2400 W' } },
    { t: 'Orvan Pour Precision Gooseneck Electric Kettle, 1L, Variable Temperature 40-100°C, Hold Mode, Stainless Steel, Brushed Finish', b: 'Orvan', p: 8900, q: 'electric kettle',
      bl: ['Counterweighted gooseneck gives real pour control', 'Set any temperature between 40 and 100°C', 'Hold mode keeps water ready for 60 minutes', 'Brushed stainless body with a cool-touch handle'],
      sp: { Brand: 'Orvan', Capacity: '1 L', 'Temperature Range': '40-100 °C', Material: 'Stainless steel' },
      v: [{ type: 'color', label: 'Brushed Steel', swatch: '#b7bbbe' }, { type: 'color', label: 'Matte Black', swatch: '#2b2b2d' }] },
    { t: 'Aureon Damascus 8" Chef Knife, 67-Layer VG-10 Core, Hand-Sharpened 15° Edge, Ergonomic Pakkawood Handle, Gift Box', b: 'Aureon', p: 11900, q: 'chef knife',
      bl: ['VG-10 core folded in 67 layers holds an edge', 'Hand-finished to 15° per side for clean slicing', 'Full tang with a triple-riveted pakkawood handle', 'Arrives in a magnetic presentation box'],
      sp: { Brand: 'Aureon', 'Blade Length': '8 inches', Steel: 'VG-10 Damascus', Hardness: '60-62 HRC', Handle: 'Pakkawood' } },
    { t: 'Vantra Hush Robot Vacuum and Mop, LiDAR Mapping, 4000Pa Suction, Self-Emptying Base, App Zones and No-Go Lines, Pet Hair Brush', b: 'Vantra', p: 39900, q: 'robot vacuum',
      bl: ['LiDAR builds an accurate multi-floor map on the first run', '4000Pa lifts embedded grit from carpet', 'Self-emptying base holds 45 days of debris', 'Tangle-resistant brush designed around pet hair'],
      sp: { Brand: 'Vantra', Suction: '4000 Pa', Navigation: 'LiDAR SLAM', 'Battery Life': '180 min', 'Dust Bag': '45 days' } },
    { t: 'Meridia Loft 3-Piece Cotton Towel Set, 700GSM Turkish Cotton, Quick Dry, OEKO-TEX Certified, Bath Hand and Face', b: 'Meridia', p: 4900, q: 'bath towels',
      bl: ['700GSM Turkish cotton that stays soft after washing', 'Twist-free loops dry faster than standard terry', 'OEKO-TEX certified with no harmful finishes', 'Bath, hand and face towel in every set'],
      sp: { Brand: 'Meridia', Material: '100% Turkish cotton', Weight: '700 GSM', Pieces: '3' },
      v: [{ type: 'color', label: 'Ivory', swatch: '#efe8dc' }, { type: 'color', label: 'Slate', swatch: '#6b7278' }, { type: 'color', label: 'Terracotta', swatch: '#b9694f' }] },
    { t: 'Brightwell Still Air Purifier for Large Rooms, True HEPA H13, Activated Carbon, 60m² Coverage, 22dB Sleep Mode, Filter Indicator', b: 'Brightwell', p: 19900, q: 'air purifier',
      bl: ['H13 HEPA captures 99.97% of particles to 0.3 microns', 'Covers rooms up to 60m² with 4.5 air changes an hour', '22dB on sleep mode, quieter than a whisper', 'Carbon layer handles cooking and pet odours'],
      sp: { Brand: 'Brightwell', 'Filter Type': 'True HEPA H13 + Carbon', Coverage: '60 m²', 'Noise Level': '22-52 dB' } },
    { t: 'Kestrel Grove Solid Oak Cutting Board with Juice Groove, Reversible, 45x30cm, Food-Safe Oil Finish, Integrated Handles', b: 'Kestrel', p: 5900, q: 'cutting board',
      bl: ['Edge-grain oak that is kind to knife edges', 'Deep juice groove on one face, flat on the other', 'Finished with food-safe oil, ready to use', 'Recessed handles make it easy to lift and carry'],
      sp: { Brand: 'Kestrel', Material: 'Solid oak', Dimensions: '45 x 30 x 3 cm', Finish: 'Food-safe mineral oil' } },
    { t: 'Orvan Daybreak Ceramic Non-Stick Frying Pan 28cm, PFAS-Free Coating, Induction Base, Oven Safe to 220°C, Stay-Cool Handle', b: 'Orvan', p: 4500, q: 'frying pan',
      bl: ['PFAS-free ceramic coating releases eggs cleanly', 'Forged aluminium body with a steel induction plate', 'Oven safe to 220°C for finishing under heat', 'Balanced stay-cool handle with a hanging loop'],
      sp: { Brand: 'Orvan', Diameter: '28 cm', Coating: 'PFAS-free ceramic', 'Oven Safe': '220 °C', Induction: 'Yes' } },
    { t: 'Lumea Halcyon Linen Duvet Cover Set, Stone-Washed French Flax, Button Closure, 2 Pillowcases, Breathable All Season', b: 'Lumea', p: 15900, q: 'bedding linen',
      bl: ['Stone-washed French flax, soft from the first night', 'Breathable enough for summer, warm enough for winter', 'Coconut button closure and interior corner ties', 'Gets softer with every wash rather than wearing out'],
      sp: { Brand: 'Lumea', Material: '100% French flax linen', Closure: 'Coconut buttons', Includes: 'Duvet cover + 2 pillowcases' },
      v: [{ type: 'size', label: 'Double', priceDelta: 0 }, { type: 'size', label: 'King', priceDelta: 3000 }, { type: 'size', label: 'Super King', priceDelta: 5500 }] },
    { t: 'Aureon Clearwater Insulated Water Bottle 750ml, Triple-Wall Vacuum, 24H Cold 12H Hot, Leakproof Lid, Powder Coat Grip', b: 'Aureon', p: 3200, q: 'water bottle',
      bl: ['Triple-wall vacuum holds cold for 24 hours', 'Leakproof lid survives a tipped-over bag', 'Powder coat gives grip and resists scratches', 'Wide mouth takes standard ice cubes'],
      sp: { Brand: 'Aureon', Capacity: '750 ml', Material: '18/8 stainless steel', Insulation: 'Triple-wall vacuum' },
      v: [{ type: 'color', label: 'Forest', swatch: '#3f5544' }, { type: 'color', label: 'Sand', swatch: '#cfc0a6' }, { type: 'color', label: 'Black', swatch: '#232325' }] },
  ],

  fashion: [
    { t: 'Nordvik Ridge Insulated Puffer Jacket, Recycled 700-Fill Down, Water-Repellent Shell, Packs Into Its Own Pocket, Unisex', b: 'Nordvik', p: 17900, q: 'winter jacket',
      bl: ['700-fill recycled down for warmth without bulk', 'DWR shell sheds drizzle and wet snow', 'Packs into the chest pocket, roughly the size of a loaf', 'Elasticated cuffs and a two-way YKK zip'],
      sp: { Brand: 'Nordvik', Fill: '700-fill recycled down', Shell: 'Recycled ripstop nylon', Fit: 'Regular' },
      v: [{ type: 'size', label: 'S' }, { type: 'size', label: 'M' }, { type: 'size', label: 'L' }, { type: 'size', label: 'XL' }] },
    { t: 'Kestrel Pace Road Running Shoes, Carbon-Infused Plate, Responsive Foam Midsole, Breathable Engineered Mesh, 248g', b: 'Kestrel', p: 13900, q: 'running shoes',
      bl: ['Carbon-infused plate returns energy on the push-off', 'Supercritical foam midsole at 248g per shoe', 'Engineered mesh upper with a padded heel collar', 'Rubber outsole pods placed where runners actually wear through'],
      sp: { Brand: 'Kestrel', Weight: '248 g', Drop: '8 mm', Upper: 'Engineered mesh', Use: 'Road running' },
      v: [{ type: 'size', label: 'UK 7' }, { type: 'size', label: 'UK 8' }, { type: 'size', label: 'UK 9' }, { type: 'size', label: 'UK 10' }, { type: 'size', label: 'UK 11' }] },
    { t: 'Orvan Everyday Merino Wool Crew T-Shirt, 17.5 Micron Superfine, Odour Resistant, Machine Washable, Regular Fit', b: 'Orvan', p: 6900, q: 't-shirt clothing',
      bl: ['17.5 micron merino with none of the itch', 'Naturally odour resistant across multiple wears', 'Machine washable on a wool cycle', 'Flatlock seams to stop pack rub on the shoulders'],
      sp: { Brand: 'Orvan', Material: '100% superfine merino wool', Weight: '170 gsm', Fit: 'Regular' },
      v: [{ type: 'color', label: 'Navy', swatch: '#26354f' }, { type: 'color', label: 'Charcoal', swatch: '#3d3f42' }, { type: 'color', label: 'Oat', swatch: '#d8cdb8' }] },
    { t: 'Aureon Field Leather Chelsea Boots, Full-Grain Leather, Goodyear Welted, Elastic Gusset, Rubber Commando Sole', b: 'Aureon', p: 22900, q: 'leather boots',
      bl: ['Full-grain leather that develops a real patina', 'Goodyear welt means they can be resoled, not binned', 'Commando rubber sole grips wet pavement', 'Elastic gussets and a pull tab for quick on and off'],
      sp: { Brand: 'Aureon', Material: 'Full-grain leather', Construction: 'Goodyear welted', Sole: 'Rubber commando' },
      v: [{ type: 'size', label: 'UK 8' }, { type: 'size', label: 'UK 9' }, { type: 'size', label: 'UK 10' }, { type: 'size', label: 'UK 11' }] },
    { t: 'Vantra Transit 22L Commuter Backpack, Padded 16" Laptop Sleeve, Water-Resistant Recycled Fabric, Luggage Pass-Through, YKK Zips', b: 'Vantra', p: 8900, q: 'backpack',
      bl: ['Suspended 16" laptop sleeve keeps the base off the floor', 'Recycled fabric with a water-resistant coating', 'Luggage pass-through slides over a case handle', 'YKK zips throughout and a quick-grab top pocket'],
      sp: { Brand: 'Vantra', Capacity: '22 L', 'Laptop Fit': 'Up to 16 inches', Material: 'Recycled polyester' },
      v: [{ type: 'color', label: 'Black', swatch: '#232326' }, { type: 'color', label: 'Olive', swatch: '#5c6244' }, { type: 'color', label: 'Navy', swatch: '#2b3a57' }] },
    { t: 'Meridia Horizon Polarised Sunglasses, UV400 Protection, Lightweight TR90 Frame, Spring Hinges, Hard Case Included', b: 'Meridia', p: 5900, q: 'sunglasses',
      bl: ['Polarised lenses cut glare off road and water', 'UV400 blocks the full UVA and UVB range', 'TR90 frame flexes instead of snapping', 'Hard case, cloth and spare nose pads included'],
      sp: { Brand: 'Meridia', 'Lens Type': 'Polarised UV400', Frame: 'TR90', Weight: '24 g' } },
    { t: 'Lumea Drift Cashmere Blend Scarf, 30% Cashmere 70% Merino, Woven Not Knitted, 180x35cm, Fringed Ends', b: 'Lumea', p: 7900, q: 'scarf',
      bl: ['Cashmere and merino blend that holds its shape', 'Woven construction drapes better than knit', 'Generous 180cm length for a proper double loop', 'Hand-finished fringed ends'],
      sp: { Brand: 'Lumea', Material: '30% cashmere, 70% merino', Dimensions: '180 x 35 cm' },
      v: [{ type: 'color', label: 'Camel', swatch: '#c19a6b' }, { type: 'color', label: 'Charcoal', swatch: '#41444a' }, { type: 'color', label: 'Burgundy', swatch: '#6d2b35' }] },
    { t: 'Brightwell Meridian Automatic Watch, 41mm Sapphire Crystal, 38-Hour Power Reserve, 100m Water Resistant, Exhibition Caseback', b: 'Brightwell', p: 34900, q: 'wrist watch',
      bl: ['Automatic movement with a 38-hour reserve', 'Sapphire crystal front and exhibition caseback', '100m water resistance with a screw-down crown', 'Quick-release strap changes without tools'],
      sp: { Brand: 'Brightwell', 'Case Diameter': '41 mm', Movement: 'Automatic', 'Water Resistance': '100 m', Crystal: 'Sapphire' } },
    { t: 'Nordvik Base Layer Thermal Set, Brushed Interior, Four-Way Stretch, Flatlock Seams, Top and Leggings, Unisex', b: 'Nordvik', p: 6400, q: 'thermal clothing',
      bl: ['Brushed interior traps warmth without adding weight', 'Four-way stretch moves with you under a shell', 'Flatlock seams sit flat under a pack', 'Top and leggings in one set'],
      sp: { Brand: 'Nordvik', Material: 'Polyester-elastane blend', Includes: 'Top + leggings', Fit: 'Athletic' },
      v: [{ type: 'size', label: 'S' }, { type: 'size', label: 'M' }, { type: 'size', label: 'L' }, { type: 'size', label: 'XL' }] },
    { t: 'Kestrel Canvas Weekender Duffel Bag 40L, Waxed Cotton, Leather Trim, Removable Shoulder Strap, Cabin Size Compatible', b: 'Kestrel', p: 12900, q: 'duffel bag',
      bl: ['Waxed cotton sheds rain and ages beautifully', 'Fits most cabin size limits at 40 litres', 'Full-grain leather handles and base corners', 'Removable padded shoulder strap'],
      sp: { Brand: 'Kestrel', Capacity: '40 L', Material: 'Waxed cotton, leather trim', Dimensions: '55 x 28 x 26 cm' } },
    { t: 'Orvan Stride Cushioned Ankle Socks 6-Pair Pack, Combed Cotton, Arch Support Band, Reinforced Heel and Toe, Breathable Mesh', b: 'Orvan', p: 2400, q: 'socks',
      bl: ['Cushioned sole with a breathable mesh instep', 'Arch support band stops the sock sliding down', 'Reinforced heel and toe where socks actually fail', 'Six pairs in one pack'],
      sp: { Brand: 'Orvan', Material: 'Combed cotton blend', Pairs: '6', Style: 'Ankle' },
      v: [{ type: 'size', label: 'UK 4-7' }, { type: 'size', label: 'UK 7-11' }, { type: 'size', label: 'UK 11-14' }] },
    { t: 'Aureon Minimal Bifold Wallet, Full-Grain Leather, RFID Blocking, 6 Card Slots, Slim 9mm Profile, Gift Boxed', b: 'Aureon', p: 4900, q: 'leather wallet',
      bl: ['Full-grain leather that softens rather than cracks', 'RFID-blocking layer built into the lining', 'Six card slots and two note compartments', 'Stays at 9mm thick when loaded'],
      sp: { Brand: 'Aureon', Material: 'Full-grain leather', 'Card Slots': '6', Thickness: '9 mm' },
      v: [{ type: 'color', label: 'Black', swatch: '#1f1f21' }, { type: 'color', label: 'Tan', swatch: '#a9754a' }] },
  ],

  sports: [
    { t: 'Kestrel Summit 65L Hiking Backpack, Adjustable Torso, Ventilated Back Panel, Rain Cover Included, Hydration Compatible', b: 'Kestrel', p: 16900, q: 'hiking backpack',
      bl: ['Adjustable torso length fits 44-56cm backs', 'Tensioned mesh panel keeps air moving behind you', 'Integrated rain cover lives in the base pocket', 'Hydration sleeve plus dual ice axe loops'],
      sp: { Brand: 'Kestrel', Capacity: '65 L', Weight: '1.9 kg', 'Torso Range': '44-56 cm' } },
    { t: 'Orvan Basecamp 2-Person Tent, 3-Season, 3000mm Hydrostatic Head, Taped Seams, Two Vestibules, Colour-Coded Poles, 2.4kg', b: 'Orvan', p: 21900, q: 'camping tent',
      bl: ['3000mm flysheet with fully taped seams', 'Two doors and two vestibules, one each', 'Colour-coded alloy poles pitch in under five minutes', '2.4kg packed, splittable between two packs'],
      sp: { Brand: 'Orvan', Capacity: '2 person', 'Packed Weight': '2.4 kg', 'Hydrostatic Head': '3000 mm', Season: '3-season' } },
    { t: 'Vantra Core Adjustable Dumbbell Set, 2.5-24kg Per Hand, Quick-Select Dial, Compact Storage Cradle, Sold as Pair', b: 'Vantra', p: 34900, q: 'dumbbells',
      bl: ['Replaces fifteen pairs of fixed dumbbells', 'Dial changes weight in 2.5kg steps in seconds', 'Cradles keep the plates tidy and off the floor', 'Knurled handle grips without tearing hands'],
      sp: { Brand: 'Vantra', 'Weight Range': '2.5-24 kg per hand', Increments: '2.5 kg', Quantity: 'Pair' } },
    { t: 'Meridia Flow Extra Thick Yoga Mat 6mm, Non-Slip TPE, Alignment Lines, Closed Cell Surface, Carry Strap Included', b: 'Meridia', p: 4900, q: 'yoga mat',
      bl: ['6mm of cushioning for knees and wrists', 'Closed-cell surface does not absorb sweat', 'Printed alignment lines help with positioning', 'TPE construction, free of PVC and latex'],
      sp: { Brand: 'Meridia', Thickness: '6 mm', Material: 'TPE', Dimensions: '183 x 61 cm' },
      v: [{ type: 'color', label: 'Slate', swatch: '#5f6a70' }, { type: 'color', label: 'Sage', swatch: '#8b9c81' }, { type: 'color', label: 'Plum', swatch: '#6d5068' }] },
    { t: 'Aureon Trail 1000 Lumen Head Torch, Rechargeable, Red Night Mode, IPX6 Rain Proof, Motion Sensor, 120g With Battery', b: 'Aureon', p: 4200, q: 'headlamp torch',
      bl: ['1000 lumen spot and flood beams in one unit', 'Wave a hand to switch modes with gloves on', 'Red mode preserves night vision in camp', 'USB-C rechargeable, 120g including the cell'],
      sp: { Brand: 'Aureon', 'Max Output': '1000 lumens', 'Water Resistance': 'IPX6', Weight: '120 g', Charging: 'USB-C' } },
    { t: 'Nordvik Ascent Insulated Sleeping Bag, Comfort -5°C, Mummy Shape, Recycled Synthetic Fill, Compression Sack Included', b: 'Nordvik', p: 13900, q: 'sleeping bag',
      bl: ['Comfort rated to -5°C for three-season use', 'Synthetic fill keeps working when damp', 'Anti-snag zip baffle and a draught collar', 'Compresses to 20x35cm in the supplied sack'],
      sp: { Brand: 'Nordvik', 'Comfort Rating': '-5 °C', Fill: 'Recycled synthetic', Shape: 'Mummy', Weight: '1.4 kg' } },
    { t: 'Brightwell Grip Resistance Band Set, 5 Levels, Natural Latex, Door Anchor and Handles, Ankle Straps, Mesh Carry Bag', b: 'Brightwell', p: 2900, q: 'resistance bands',
      bl: ['Five bands from 4.5kg to 27kg, stackable', 'Natural latex layered to resist snapping', 'Door anchor opens up full-body movements', 'Everything packs into the mesh bag for travel'],
      sp: { Brand: 'Brightwell', Bands: '5', 'Resistance Range': '4.5-27 kg', Material: 'Natural latex' } },
    { t: 'Lumea Recover Foam Massage Roller, High Density EVA, Textured Trigger Point Grid, 33cm, Supports 150kg', b: 'Lumea', p: 3400, q: 'foam roller',
      bl: ['Textured grid mimics a therapist thumb and palm', 'High-density EVA holds shape rather than flattening', 'Hollow core rated to 150kg', '33cm length works for legs, back and lats'],
      sp: { Brand: 'Lumea', Length: '33 cm', Material: 'High-density EVA', 'Max Load': '150 kg' } },
    { t: 'Kestrel Glide Folding Trekking Poles, Carbon Fibre, 3-Section Z-Fold, Cork Grips, Tungsten Tips, 480g Pair', b: 'Kestrel', p: 9900, q: 'trekking poles',
      bl: ['Carbon shafts at 480g for the pair', 'Z-fold collapses to 38cm for pack stowage', 'Cork grips absorb sweat and mould to the hand', 'Tungsten tips plus rubber feet and snow baskets'],
      sp: { Brand: 'Kestrel', Material: 'Carbon fibre', 'Folded Length': '38 cm', Weight: '480 g pair' } },
    { t: 'Orvan Current Insulated Cooler Backpack 25L, Leakproof Liner, Holds 30 Cans, 24H Ice Retention, Padded Straps', b: 'Orvan', p: 7900, q: 'cooler bag',
      bl: ['Welded leakproof liner holds melted ice, not your car', 'Keeps ice for 24 hours in summer heat', 'Holds 30 cans plus a dry compartment on top', 'Padded straps make a full load carryable'],
      sp: { Brand: 'Orvan', Capacity: '25 L', 'Ice Retention': '24 hours', Liner: 'Welded leakproof' } },
    { t: 'Vantra Circuit Weighted Jump Rope, Ball Bearing Handles, Adjustable Steel Cable, Removable 150g Weights, Carry Pouch', b: 'Vantra', p: 2200, q: 'jump rope',
      bl: ['Ball bearings keep the rotation smooth at speed', 'Removable handle weights change the workout', 'Steel cable cuts to your exact height', 'Fits in a pocket of any gym bag'],
      sp: { Brand: 'Vantra', 'Cable Length': '3 m adjustable', Weights: '2x 150 g removable', Bearings: 'Sealed ball' } },
    { t: 'Meridia Depth Swimming Goggles, Anti-Fog Coated Lenses, Silicone Double Seal, UV Protection, 4 Nose Bridges, Case', b: 'Meridia', p: 2600, q: 'swimming goggles',
      bl: ['Anti-fog coating that survives more than one session', 'Double silicone seal holds without leaving rings', 'Four nose bridges included for a proper fit', 'UV-protective tinted lenses for outdoor pools'],
      sp: { Brand: 'Meridia', 'Lens Type': 'Anti-fog, UV tinted', Seal: 'Double silicone', Includes: '4 nose bridges, case' } },
  ],

  beauty: [
    { t: 'Lumea Renew Vitamin C Brightening Serum 30ml, 15% L-Ascorbic Acid with Ferulic Acid and Vitamin E, Fragrance Free', b: 'Lumea', p: 3900, q: 'skincare serum',
      bl: ['15% L-ascorbic acid stabilised with ferulic acid', 'Targets uneven tone and dullness over 8-12 weeks', 'Fragrance free and suitable for sensitive skin', 'Amber glass bottle protects the formula from light'],
      sp: { Brand: 'Lumea', Volume: '30 ml', 'Key Ingredient': '15% L-Ascorbic Acid', 'Skin Type': 'All, including sensitive' } },
    { t: 'Aureon Hydra Ceramide Moisturiser 50ml, Hyaluronic Acid and Niacinamide, Non-Comedogenic, 24H Barrier Support', b: 'Aureon', p: 2900, q: 'face cream',
      bl: ['Three ceramides rebuild a compromised skin barrier', 'Hyaluronic acid draws water into the upper layers', 'Non-comedogenic and safe under makeup or SPF', 'Unscented, with no essential oils or alcohol'],
      sp: { Brand: 'Aureon', Volume: '50 ml', 'Key Ingredients': 'Ceramides, HA, Niacinamide', Finish: 'Matte' } },
    { t: 'Kestrel Precision Cordless Hair Clipper Kit, Titanium Blades, 10 Guide Combs, 180min Runtime, LED Charge Display, Travel Case', b: 'Kestrel', p: 6900, q: 'hair clipper',
      bl: ['Titanium-coated blades stay sharp and run cool', 'Ten guards from 1.5mm to 25mm', '180 minutes of cordless runtime per charge', 'Zip case holds every attachment in place'],
      sp: { Brand: 'Kestrel', Runtime: '180 minutes', Blades: 'Titanium-coated steel', Guards: '10' } },
    { t: 'Vantra Ionic Hair Dryer 1800W, Ceramic Tourmaline, 3 Heat 2 Speed Settings, Cool Shot, Diffuser and Concentrator', b: 'Vantra', p: 5900, q: 'hair dryer',
      bl: ['Ionic output cuts frizz and static as it dries', 'Ceramic tourmaline grille spreads heat evenly', 'Diffuser and concentrator nozzles both included', 'Removable filter you can actually clean'],
      sp: { Brand: 'Vantra', Power: '1800 W', Settings: '3 heat, 2 speed', Attachments: 'Diffuser, concentrator' } },
    { t: 'Nordvik Ritual Sandalwood and Cedar Eau de Parfum 50ml, Woody Amber Notes, 8-Hour Wear, Vegan and Cruelty Free', b: 'Nordvik', p: 8900, q: 'perfume bottle',
      bl: ['Opens with bergamot, settles into sandalwood and cedar', 'Eau de parfum concentration, roughly 8 hours of wear', 'Vegan, cruelty free and never tested on animals', 'Refillable heavy glass flacon'],
      sp: { Brand: 'Nordvik', Volume: '50 ml', Concentration: 'Eau de Parfum', 'Scent Family': 'Woody Amber' } },
    { t: 'Meridia Detail 12-Piece Makeup Brush Set, Synthetic Vegan Bristles, Ergonomic Handles, Magnetic Storage Case', b: 'Meridia', p: 3400, q: 'makeup brushes',
      bl: ['Twelve brushes covering face and full eye work', 'Synthetic bristles that do not shed into product', 'Tapered handles stay balanced in the hand', 'Magnetic case keeps shapes intact in a bag'],
      sp: { Brand: 'Meridia', Pieces: '12', Bristles: 'Synthetic vegan', Includes: 'Magnetic case' } },
    { t: 'Orvan Clear Salicylic Acid Cleanser 200ml, 2% BHA, Gentle Foaming, pH Balanced, Daily Use for Oily and Combination Skin', b: 'Orvan', p: 2200, q: 'face wash',
      bl: ['2% salicylic acid clears pores without stripping', 'pH balanced at 5.5 to protect the barrier', 'Low-foam formula rinses clean with no residue', 'Suitable for daily morning and evening use'],
      sp: { Brand: 'Orvan', Volume: '200 ml', 'Active Ingredient': '2% Salicylic Acid', 'Skin Type': 'Oily, combination' } },
    { t: 'Brightwell Glow LED Vanity Mirror, 3 Light Temperatures, Touch Dimming, 10x Magnification Spot, Rechargeable, 360° Rotation', b: 'Brightwell', p: 5400, q: 'vanity mirror',
      bl: ['Three colour temperatures for day, evening and neutral', 'Touch bar dims smoothly rather than in steps', 'Detachable 10x magnetic spot mirror', 'USB-C rechargeable, no trailing cable in use'],
      sp: { Brand: 'Brightwell', Diameter: '20 cm', 'Colour Modes': '3', Magnification: '10x spot', Charging: 'USB-C' } },
    { t: 'Aureon Silk Pillowcase Pair, 22 Momme Mulberry Silk, Hidden Zip, OEKO-TEX Certified, Kind to Hair and Skin', b: 'Aureon', p: 6900, q: 'silk pillowcase',
      bl: ['22 momme mulberry silk on both faces, not just one', 'Reduces friction that causes bed hair and creasing', 'Hidden zip keeps the pillow in place overnight', 'OEKO-TEX certified and machine washable on delicate'],
      sp: { Brand: 'Aureon', Material: '100% Mulberry Silk', Weight: '22 momme', Quantity: 'Pair' },
      v: [{ type: 'color', label: 'Ivory', swatch: '#f0e9dd' }, { type: 'color', label: 'Charcoal', swatch: '#44474c' }, { type: 'color', label: 'Blush', swatch: '#e3c3bd' }] },
    { t: 'Lumea Smooth IPL Hair Removal Handset, 500,000 Flashes, 5 Intensity Levels, Skin Tone Sensor, Corded, Body and Face Heads', b: 'Lumea', p: 17900, q: 'beauty device',
      bl: ['500,000 flashes, enough for years of full-body use', 'Skin tone sensor blocks unsafe intensity settings', 'Glide mode for legs, stamp mode for face and underarms', 'Corded, so there is no battery to degrade'],
      sp: { Brand: 'Lumea', Flashes: '500,000', 'Intensity Levels': '5', Heads: 'Body + facial' } },
    { t: 'Kestrel Daily Mineral Sunscreen SPF 50 PA++++, Non-Greasy Zinc Oxide, No White Cast, Reef Safe, 60ml', b: 'Kestrel', p: 2400, q: 'sunscreen',
      bl: ['Mineral zinc oxide with a tint that avoids white cast', 'SPF 50 PA++++ broad spectrum protection', 'Sits well under makeup without pilling', 'Reef safe, free of oxybenzone and octinoxate'],
      sp: { Brand: 'Kestrel', Volume: '60 ml', SPF: '50 PA++++', Type: 'Mineral (Zinc Oxide)' } },
    { t: 'Vantra Sonic Electric Toothbrush, 40,000 Strokes Per Minute, 5 Modes, Pressure Sensor, 4 Heads, 30-Day Battery, Travel Case', b: 'Vantra', p: 6400, q: 'electric toothbrush',
      bl: ['40,000 sonic strokes a minute with a 2-minute timer', 'Pressure sensor lights up before you damage gums', 'Five modes including sensitive and gum care', '30 days per charge with four heads in the box'],
      sp: { Brand: 'Vantra', Strokes: '40,000/min', Modes: '5', 'Battery Life': '30 days', Heads: '4' } },
  ],

  toys: [
    { t: 'Orvan Citadel 1,200-Piece Architecture Building Block Set, Ages 9+, Compatible With Major Brick Brands, Display Base Included', b: 'Orvan', p: 8900, q: 'building blocks toy',
      bl: ['1,200 precision-moulded bricks with a display base', 'Clutch power compatible with the bricks you own', 'Illustrated 90-page step-by-step booklet', 'Recommended for ages 9 and up'],
      sp: { Brand: 'Orvan', Pieces: '1200', 'Age Range': '9+', Includes: 'Display base, booklet' } },
    { t: 'Meridia Hoard Family Strategy Board Game, 2-5 Players, 45-60 Minutes, Ages 10+, Double-Sided Board, 120 Cards', b: 'Meridia', p: 4400, q: 'board game',
      bl: ['Plays in 45-60 minutes, short enough for a weeknight', 'Double-sided board changes the map between games', 'Rules teach in five minutes with a reference card each', 'Insert keeps components sorted between sessions'],
      sp: { Brand: 'Meridia', Players: '2-5', 'Play Time': '45-60 min', 'Age Range': '10+' } },
    { t: 'Kestrel Voyager Remote Control Drone with 1080p Camera, Altitude Hold, One-Key Takeoff, 3 Batteries, 36 Min Total Flight', b: 'Kestrel', p: 11900, q: 'drone toy',
      bl: ['1080p camera streams live to your phone', 'Altitude hold makes it genuinely flyable by beginners', 'Three batteries give 36 minutes in the air', 'Folds into the supplied hard case'],
      sp: { Brand: 'Kestrel', Camera: '1080p', 'Flight Time': '12 min per battery', Batteries: '3', 'Age Range': '14+' } },
    { t: 'Lumea Galaxy 1000-Piece Jigsaw Puzzle, 68x48cm Finished Size, Premium Linen Finish, Poster Guide and Sorting Trays', b: 'Lumea', p: 2200, q: 'jigsaw puzzle',
      bl: ['Linen finish cuts glare under a lamp', 'Precision die cut, so pieces click rather than wedge', 'Full-size poster included for reference', 'Six sorting trays in the box'],
      sp: { Brand: 'Lumea', Pieces: '1000', 'Finished Size': '68 x 48 cm', 'Age Range': '12+' } },
    { t: 'Vantra Junior STEM Robotics Kit, 12 Buildable Models, Screw-Free Assembly, App Coding Lessons, Ages 6-10, Rechargeable', b: 'Vantra', p: 7900, q: 'robot toy',
      bl: ['Twelve models from one kit, rebuilt not replaced', 'Screw-free parts small hands can actually assemble', 'App teaches block coding through 20 lessons', 'Rechargeable core, no endless AA batteries'],
      sp: { Brand: 'Vantra', Models: '12', 'Age Range': '6-10', Power: 'Rechargeable' } },
    { t: 'Aureon Explorer Wooden Play Kitchen, Solid Birch, Turning Dials, Chalkboard Panel, 15 Accessories, Ages 3+', b: 'Aureon', p: 14900, q: 'wooden toy',
      bl: ['Solid birch rather than printed particle board', 'Dials click and the tap turns, as children expect', 'Fifteen wooden accessories included', 'Rounded edges and non-toxic water-based paint'],
      sp: { Brand: 'Aureon', Material: 'Solid birch', 'Age Range': '3+', Accessories: '15 pieces' } },
    { t: 'Nordvik Night Sky Projector and Sleep Soother, 8 Colour Modes, White Noise Library, Timer, Remote Control, USB-C', b: 'Nordvik', p: 3900, q: 'night light',
      bl: ['Projects stars and nebula across a whole ceiling', 'Eight colour modes with adjustable brightness', 'Twelve white noise and lullaby tracks built in', '30, 60 and 90 minute sleep timers'],
      sp: { Brand: 'Nordvik', 'Colour Modes': '8', Sounds: '12', Power: 'USB-C', Timer: '30/60/90 min' } },
    { t: 'Brightwell Tumble Kids Scooter, 3 Wheels, Lean-to-Steer, Adjustable Height, Light-Up Wheels, Ages 3-8, Holds 50kg', b: 'Brightwell', p: 5400, q: 'kids scooter',
      bl: ['Lean-to-steer builds balance more naturally than handlebars', 'Height adjusts across four positions as they grow', 'Wheels light up from motion, no batteries needed', 'Rear brake and a 50kg weight limit'],
      sp: { Brand: 'Brightwell', 'Age Range': '3-8', 'Max Load': '50 kg', Wheels: '3, light-up' } },
    { t: 'Kestrel Discovery Kids Microscope Set, 100x-1200x Magnification, 48 Accessories, Prepared Slides, Smartphone Adapter', b: 'Kestrel', p: 6400, q: 'microscope',
      bl: ['100x to 1200x with real glass optics', 'Smartphone adapter lets them photograph specimens', '48 accessories including 12 prepared slides', 'LED illumination from above and below'],
      sp: { Brand: 'Kestrel', Magnification: '100x-1200x', Accessories: '48', 'Age Range': '8+' } },
    { t: 'Orvan Playtime Plush Bear 40cm, Hypoallergenic Fill, Machine Washable, Embroidered Features, Suitable From Birth', b: 'Orvan', p: 2400, q: 'teddy bear',
      bl: ['Embroidered features, so nothing can be pulled loose', 'Hypoallergenic fill, safe from birth', 'Machine washable at 30°C and keeps its shape', 'Weighted base so it sits up on a shelf'],
      sp: { Brand: 'Orvan', Height: '40 cm', Fill: 'Hypoallergenic polyester', 'Age Range': '0+' },
      v: [{ type: 'color', label: 'Honey', swatch: '#c89a5b' }, { type: 'color', label: 'Cocoa', swatch: '#6b4b35' }, { type: 'color', label: 'Cream', swatch: '#e6dcc8' }] },
    { t: 'Meridia Card Deck Classic Playing Cards 2-Pack, Linen Air-Cushion Finish, Casino Grade, Poker Size, Tuck Boxes', b: 'Meridia', p: 1200, q: 'playing cards',
      bl: ['Air-cushion finish for a clean riffle shuffle', 'Casino-grade stock survives real handling', 'Two decks, one red and one blue', 'Standard poker size with large indices'],
      sp: { Brand: 'Meridia', Decks: '2', Size: 'Poker', Finish: 'Linen air-cushion' } },
    { t: 'Lumea Art Studio 150-Piece Drawing Set, Coloured Pencils Pastels and Watercolours, Wooden Case, Ages 6+', b: 'Lumea', p: 4200, q: 'art supplies',
      bl: ['150 pieces spanning pencils, pastels and watercolour', 'Hinged wooden case keeps everything in its slot', 'Pre-sharpened, break-resistant pencil cores', 'Non-toxic and conforms to EN71 safety standards'],
      sp: { Brand: 'Lumea', Pieces: '150', 'Age Range': '6+', Case: 'Wooden hinged' } },
  ],

  books: [
    { t: 'The Quiet Algorithm: How Small Systems Shape Big Decisions - Hardcover, 384 Pages', b: 'Harrowgate Press', p: 2200, q: 'book cover',
      bl: ['A readable tour of the systems running underneath daily life', '384 pages with notes and a full index', 'Sewn hardcover binding that opens flat', 'Named a book of the year by three trade reviews'],
      sp: { Publisher: 'Harrowgate Press', Format: 'Hardcover', Pages: '384', Language: 'English' } },
    { t: 'Northlight - A Novel of the Coast - Paperback, 312 Pages, Winner of the Ashcroft Fiction Prize', b: 'Ashgrove Books', p: 1100, q: 'novel book',
      bl: ['Prize-winning literary fiction set over one winter', '312 pages, paperback with French flaps', 'Includes a new afterword from the author', 'Reading group questions at the back'],
      sp: { Publisher: 'Ashgrove Books', Format: 'Paperback', Pages: '312', Language: 'English' } },
    { t: 'The Practical Kitchen: 200 Recipes for Weeknight Cooking - Hardcover, Full Colour Photography, 448 Pages', b: 'Harrowgate Press', p: 3200, q: 'cookbook',
      bl: ['200 recipes built around a 30-minute weeknight', 'A full-colour photograph for every single dish', 'Lay-flat binding that survives a working kitchen', 'Substitution notes on every page'],
      sp: { Publisher: 'Harrowgate Press', Format: 'Hardcover', Pages: '448', Illustrations: 'Full colour' } },
    { t: 'Grid and Rhythm: Foundations of Layout Design - Paperback, 280 Pages, 400 Illustrations, Third Edition', b: 'Plinth Editions', p: 3800, q: 'design book',
      bl: ['The standard layout reference, now in a third edition', '400 annotated illustrations and worked examples', 'New chapter on responsive and variable type', 'Used on design courses in over 40 countries'],
      sp: { Publisher: 'Plinth Editions', Format: 'Paperback', Pages: '280', Edition: 'Third' } },
    { t: 'Atlas of Small Places: 80 Overlooked Corners of the World - Hardcover, Illustrated Maps, 264 Pages', b: 'Plinth Editions', p: 2900, q: 'atlas map book',
      bl: ['Eighty places most atlases leave out entirely', 'Hand-drawn maps commissioned for this edition', 'Foil-stamped cloth cover with a ribbon marker', 'A genuinely good gift for the travelled'],
      sp: { Publisher: 'Plinth Editions', Format: 'Hardcover', Pages: '264', Maps: 'Illustrated' } },
    { t: 'The Long Field - Historical Fiction, Paperback, 528 Pages, Book One of the Wintermark Trilogy', b: 'Ashgrove Books', p: 1300, q: 'paperback book',
      bl: ['Opening volume of a completed three-book trilogy', '528 pages with a map and family tree', 'Over 40,000 ratings across retailers', 'Books two and three both available now'],
      sp: { Publisher: 'Ashgrove Books', Format: 'Paperback', Pages: '528', Series: 'Wintermark #1' } },
    { t: 'First Words: A Read-Aloud Picture Book for Ages 2-5 - Board Book, 32 Thick Pages, Wipe Clean', b: 'Brambleton Kids', p: 900, q: 'childrens book',
      bl: ['Thick board pages that survive a determined toddler', 'Wipe-clean finish for the inevitable', '32 pages of read-aloud rhyme', 'Rounded corners throughout'],
      sp: { Publisher: 'Brambleton Kids', Format: 'Board book', Pages: '32', 'Age Range': '2-5' } },
    { t: 'Deep Work Habits: A Field Guide to Focused Attention - Paperback, 296 Pages, Includes 12-Week Programme', b: 'Harrowgate Press', p: 1600, q: 'self help book',
      bl: ['A structured 12-week programme, not just theory', '296 pages with worksheets you can photocopy', 'Draws on published attention research throughout', 'Companion audio available separately'],
      sp: { Publisher: 'Harrowgate Press', Format: 'Paperback', Pages: '296', Includes: '12-week programme' } },
    { t: 'The Gardener Year: Month by Month in a Temperate Garden - Hardcover, 360 Pages, Botanical Illustrations', b: 'Plinth Editions', p: 3400, q: 'gardening book',
      bl: ['Organised by month, so it stays useful all year', '360 pages of botanical illustration throughout', 'Regional notes for cooler and warmer zones', 'Cloth-bound with a planting-record section'],
      sp: { Publisher: 'Plinth Editions', Format: 'Hardcover', Pages: '360', Illustrations: 'Botanical plates' } },
    { t: 'Nightjar - Crime Thriller, Paperback, 368 Pages, The First Inspector Vale Mystery', b: 'Ashgrove Books', p: 1000, q: 'thriller book',
      bl: ['First in a series of six Inspector Vale mysteries', '368 pages, paperback', 'Optioned for television adaptation', 'A proper puzzle plot that plays fair with the reader'],
      sp: { Publisher: 'Ashgrove Books', Format: 'Paperback', Pages: '368', Series: 'Inspector Vale #1' } },
    { t: 'Everyday Physics Explained: 100 Questions About How Things Work - Paperback, 320 Pages, Diagrams Throughout', b: 'Harrowgate Press', p: 1800, q: 'science book',
      bl: ['100 self-contained answers, readable in any order', 'Clear diagrams rather than equations', '320 pages suitable for curious teens and adults', 'Glossary and further reading for every chapter'],
      sp: { Publisher: 'Harrowgate Press', Format: 'Paperback', Pages: '320', Language: 'English' } },
    { t: 'Undated Daily Planner and Journal, Hardcover, 200 Lined and Dotted Pages, Ribbon Marker, Elastic Closure, A5', b: 'Brambleton Kids', p: 1500, q: 'notebook journal',
      bl: ['Undated, so it never goes to waste', '200 pages split between lined and dotted', '100gsm paper that fountain pens do not bleed through', 'Ribbon marker, elastic closure and a rear pocket'],
      sp: { Publisher: 'Brambleton', Format: 'Hardcover', Pages: '200', Size: 'A5' } },
  ],

  office: [
    { t: 'Meridia Poise Ergonomic Mesh Office Chair, Adjustable Lumbar Support, 4D Armrests, Tilt Lock, Breathable Back, Holds 136kg', b: 'Meridia', p: 27900, q: 'office chair',
      bl: ['Independently adjustable lumbar pad, not a fixed bump', '4D armrests move up, in, forward and rotate', 'Tilt lock with four positions and tension control', 'Breathable mesh back rated to 136kg'],
      sp: { Brand: 'Meridia', 'Max Load': '136 kg', Armrests: '4D adjustable', Back: 'Breathable mesh', Warranty: '5 years' } },
    { t: 'Kestrel Level Electric Standing Desk 140x70cm, Dual Motor, 4 Memory Presets, 125kg Capacity, Anti-Collision, Cable Tray', b: 'Kestrel', p: 44900, q: 'standing desk',
      bl: ['Dual motors lift 125kg smoothly and quietly', 'Four memory presets for different users and postures', 'Anti-collision stops the desk crushing what is beneath', 'Cable tray and grommets included in the box'],
      sp: { Brand: 'Kestrel', 'Desktop Size': '140 x 70 cm', 'Height Range': '72-122 cm', 'Max Load': '125 kg', Motors: 'Dual' } },
    { t: 'Orvan Everyday Gel Pen 20-Pack, 0.5mm Needle Tip, Quick-Dry Smudge-Proof Ink, Comfort Grip, Black', b: 'Orvan', p: 1400, q: 'pens stationery',
      bl: ['0.5mm needle tip for genuinely fine lines', 'Quick-dry ink that left-handers can live with', 'Cushioned grip for long writing sessions', 'Twenty pens per box'],
      sp: { Brand: 'Orvan', 'Tip Size': '0.5 mm', Quantity: '20', 'Ink Colour': 'Black' } },
    { t: 'Aureon Clarity A4 Document Shredder, Cross-Cut P-4 Security, 12 Sheets, 20L Bin, Credit Card and Staple Safe, Overheat Protection', b: 'Aureon', p: 9900, q: 'paper shredder',
      bl: ['P-4 cross-cut leaves 4x40mm particles, not strips', 'Handles 12 sheets, staples, cards and CDs', '20 litre pull-out bin with a window', 'Thermal protection and auto reverse for jams'],
      sp: { Brand: 'Aureon', 'Security Level': 'P-4 Cross-cut', Capacity: '12 sheets', 'Bin Size': '20 L' } },
    { t: 'Vantra Focus Desk Organiser with Drawer, Bamboo and Steel, Pen Slots, Phone Dock, Card Holder, Compact Footprint', b: 'Vantra', p: 3400, q: 'desk organizer',
      bl: ['Bamboo and powder-coated steel, not plastic', 'Sliding drawer for the clutter you cannot display', 'Dock angles a phone for glanceable notifications', 'Small footprint that leaves the desk usable'],
      sp: { Brand: 'Vantra', Material: 'Bamboo, powder-coated steel', Dimensions: '28 x 14 x 12 cm' } },
    { t: 'Nordvik Archive Hanging File Box with Lid, Reinforced Fibreboard, Holds A4 and Foolscap, Stackable, Pack of 5', b: 'Nordvik', p: 2900, q: 'file storage box',
      bl: ['Reinforced fibreboard that holds shape when full', 'Takes both A4 and foolscap hanging files', 'Stacks four high without bowing', 'Flat-packed, assembles without tape'],
      sp: { Brand: 'Nordvik', Quantity: '5', 'Fits Files': 'A4 and Foolscap', Material: 'Reinforced fibreboard' } },
    { t: 'Brightwell Beam LED Desk Lamp with USB-C Charging Port, 5 Colour Modes, Touch Dimming, Memory Function, Adjustable Arm', b: 'Brightwell', p: 4400, q: 'desk lamp',
      bl: ['Five colour temperatures with stepless dimming', 'Remembers your last setting when switched on', 'USB-C port charges a phone from the base', 'Weighted base and a fully articulated arm'],
      sp: { Brand: 'Brightwell', 'Colour Modes': '5', Power: '12 W', Extras: 'USB-C charging port' } },
    { t: 'Lumea Quiet Acoustic Desk Divider Panel, Recycled PET Felt, Clamp Mount, 60x40cm, Pinnable Surface, 5 Colours', b: 'Lumea', p: 5900, q: 'office partition',
      bl: ['Recycled PET felt genuinely reduces desk-level noise', 'Clamps to any desktop up to 4cm thick', 'Pinnable surface doubles as a notes board', 'No tools required to fit or move'],
      sp: { Brand: 'Lumea', Dimensions: '60 x 40 cm', Material: 'Recycled PET felt', Mount: 'Clamp' },
      v: [{ type: 'color', label: 'Slate', swatch: '#5c626a' }, { type: 'color', label: 'Moss', swatch: '#6f7f63' }, { type: 'color', label: 'Rust', swatch: '#a8563c' }] },
    { t: 'Kestrel Sort A4 Laminator, 3-Minute Warm Up, 80-125 Micron Pouches, Jam Release, Includes 25 Pouches', b: 'Kestrel', p: 3900, q: 'laminator office',
      bl: ['Ready in three minutes rather than ten', 'Takes 80 to 125 micron pouches, A4 and smaller', 'Jam release lever recovers a misfeed instantly', 'Twenty-five pouches included to start'],
      sp: { Brand: 'Kestrel', 'Max Width': 'A4', 'Pouch Thickness': '80-125 micron', 'Warm Up': '3 minutes' } },
    { t: 'Orvan Stack Letter Tray Set of 3, Powder-Coated Steel Mesh, Interlocking Stackable Design, A4, Non-Slip Feet', b: 'Orvan', p: 2600, q: 'letter tray',
      bl: ['Interlocks so the stack cannot be knocked apart', 'Powder-coated steel mesh, not flexing plastic', 'Takes A4 and letter without overhang', 'Non-slip feet protect the desk surface'],
      sp: { Brand: 'Orvan', Quantity: '3', Material: 'Powder-coated steel', Size: 'A4' } },
    { t: 'Meridia Trace Dry Erase Whiteboard 90x60cm, Magnetic Surface, Aluminium Frame, Pen Tray, Wall Mount Kit Included', b: 'Meridia', p: 4900, q: 'whiteboard',
      bl: ['Magnetic lacquered steel wipes fully clean', 'Aluminium frame with rounded safety corners', 'Full-width pen tray along the bottom edge', 'Portrait or landscape mounting hardware included'],
      sp: { Brand: 'Meridia', Dimensions: '90 x 60 cm', Surface: 'Magnetic lacquered steel', Frame: 'Aluminium' } },
    { t: 'Aureon Pace Weekly Desk Pad Planner, 52 Undated Tear-Off Sheets, A3, Recycled 120gsm Paper, Habit Tracker Column', b: 'Aureon', p: 1900, q: 'desk planner',
      bl: ['52 undated sheets, start any week of the year', 'A3 sits under a monitor without wasting desk', '120gsm recycled stock that takes fountain pen', 'Habit tracker and priorities column built in'],
      sp: { Brand: 'Aureon', Sheets: '52', Size: 'A3', Paper: '120 gsm recycled' } },
  ],

  pets: [
    { t: 'Brightwell Den Orthopaedic Memory Foam Dog Bed, Large, Water-Resistant Liner, Removable Washable Cover, Non-Slip Base', b: 'Brightwell', p: 8900, q: 'dog bed',
      bl: ['Single-piece orthopaedic foam, not shredded filler', 'Water-resistant inner liner protects the foam', 'Cover unzips and machine washes at 40°C', 'Bolstered sides for dogs that like to lean'],
      sp: { Brand: 'Brightwell', Size: 'Large (100 x 70 cm)', Fill: 'Orthopaedic memory foam', Cover: 'Removable, machine washable' },
      v: [{ type: 'size', label: 'Medium', priceDelta: -2000 }, { type: 'size', label: 'Large', priceDelta: 0 }, { type: 'size', label: 'X-Large', priceDelta: 3000 }] },
    { t: 'Vantra Spring Stainless Steel Pet Water Fountain 2.5L, Ultra-Quiet Pump, Triple Filtration, LED Level Indicator, Dishwasher Safe', b: 'Vantra', p: 5900, q: 'pet water fountain',
      bl: ['Stainless steel bowl resists the biofilm plastic grows', 'Pump runs under 30dB, quiet enough for a bedroom', 'Triple filter removes hair, debris and odour', 'LED warns before the reservoir runs dry'],
      sp: { Brand: 'Vantra', Capacity: '2.5 L', Material: 'Stainless steel', 'Noise Level': '<30 dB' } },
    { t: 'Kestrel Trail No-Pull Dog Harness, Padded Chest Plate, Reflective Stitching, 4 Adjustment Points, Front and Back Clips', b: 'Kestrel', p: 3900, q: 'dog harness',
      bl: ['Front clip discourages pulling without choking', 'Four adjustment points for a genuinely custom fit', 'Reflective stitching on every strap for night walks', 'Padded chest plate spreads load across the sternum'],
      sp: { Brand: 'Kestrel', Clips: 'Front and back', Adjustment: '4 points', Reflective: 'Yes' },
      v: [{ type: 'size', label: 'S' }, { type: 'size', label: 'M' }, { type: 'size', label: 'L' }, { type: 'size', label: 'XL' }] },
    { t: 'Orvan Perch Modular Cat Tree, 150cm, Sisal Scratching Posts, Two Hammocks, Replaceable Parts, Solid Wood Frame', b: 'Orvan', p: 12900, q: 'cat tree',
      bl: ['Solid wood frame rather than cardboard tube', 'Every post and platform is individually replaceable', 'Natural sisal that cats prefer to carpet', 'Two hammocks rated to 9kg each'],
      sp: { Brand: 'Orvan', Height: '150 cm', Material: 'Solid wood, sisal, plush', 'Max Load': '9 kg per hammock' } },
    { t: 'Meridia Measure Automatic Pet Feeder 6L, Programmable 4 Meals Daily, Voice Recorder, Battery Backup, Portion Control', b: 'Meridia', p: 8400, q: 'pet feeder',
      bl: ['Up to four meals a day with 1-10 portion sizing', 'Records a ten-second call to the bowl', 'Battery backup keeps the schedule through a power cut', 'Sealed hopper with a desiccant slot'],
      sp: { Brand: 'Meridia', Capacity: '6 L', Meals: 'Up to 4 daily', Power: 'Mains + battery backup' } },
    { t: 'Nordvik Groom Deshedding Brush for Dogs and Cats, Stainless Steel Comb, Self-Cleaning Release Button, Anti-Slip Handle', b: 'Nordvik', p: 2200, q: 'pet grooming brush',
      bl: ['Reaches the undercoat without cutting guard hairs', 'One button ejects the collected fur', 'Rounded tooth ends will not scratch skin', 'Works on both double and single coats'],
      sp: { Brand: 'Nordvik', Material: 'Stainless steel, TPR handle', 'Blade Width': '10 cm', 'Self-Cleaning': 'Yes' } },
    { t: 'Aureon Tumble Interactive Treat Dispensing Dog Toy, Adjustable Difficulty, Natural Rubber, Dishwasher Safe, Medium', b: 'Aureon', p: 1900, q: 'dog toy',
      bl: ['Adjustable aperture changes how hard the puzzle is', 'Food-grade natural rubber with no fillers', 'Wobbles unpredictably to hold interest', 'Goes on the top rack of the dishwasher'],
      sp: { Brand: 'Aureon', Material: 'Natural rubber', Size: 'Medium', 'Dishwasher Safe': 'Yes' } },
    { t: 'Lumea Carry Airline Approved Pet Carrier, Mesh Ventilation on 4 Sides, Fleece Base, Seatbelt Strap, Fits Under Seat', b: 'Lumea', p: 6400, q: 'pet carrier',
      bl: ['Sized to most airline under-seat limits', 'Mesh on four sides keeps air moving', 'Removable fleece base washes at 30°C', 'Seatbelt loop and a safety tether inside'],
      sp: { Brand: 'Lumea', Dimensions: '45 x 28 x 25 cm', 'Max Pet Weight': '8 kg', Base: 'Removable fleece' } },
    { t: 'Kestrel Clean Cat Litter Mat, Double Layer Honeycomb Trap, Waterproof Backing, 75x55cm, Easy Shake Out', b: 'Kestrel', p: 2400, q: 'cat litter mat',
      bl: ['Honeycomb top layer traps litter between the sheets', 'Open one side and tip the collected grit back', 'Waterproof backing stops seepage to the floor', 'Soft enough that cats will actually walk on it'],
      sp: { Brand: 'Kestrel', Dimensions: '75 x 55 cm', Layers: 'Double honeycomb', Backing: 'Waterproof EVA' } },
    { t: 'Orvan Reflect LED Dog Collar, USB-C Rechargeable, 3 Light Modes, Visible to 500m, Water Resistant, Adjustable', b: 'Orvan', p: 2100, q: 'dog collar',
      bl: ['Visible from up to 500 metres on dark lanes', 'Three modes: steady, slow flash and fast flash', 'USB-C rechargeable, around 10 hours per charge', 'Water resistant for wet walks and puddles'],
      sp: { Brand: 'Orvan', Modes: '3', Visibility: '500 m', Charging: 'USB-C' },
      v: [{ type: 'size', label: 'S (30-40cm)' }, { type: 'size', label: 'M (40-50cm)' }, { type: 'size', label: 'L (50-60cm)' }] },
    { t: 'Vantra Fresh Odour-Sealing Pet Waste Bags, 720 Bags, 15 Micron Thick, Unscented, Leak Proof, Refill Rolls', b: 'Vantra', p: 1700, q: 'pet waste bags',
      bl: ['15 micron film that does not tear at the knot', 'Odour-sealing layer, genuinely unscented', '720 bags across 48 refill rolls', 'Fits every standard bag dispenser'],
      sp: { Brand: 'Vantra', Quantity: '720 bags', Thickness: '15 micron', Rolls: '48' } },
    { t: 'Meridia Sound Pet Hair Remover Roller, Reusable No Refills Needed, Self-Cleaning Base, Works on Fabric and Upholstery', b: 'Meridia', p: 1800, q: 'lint roller',
      bl: ['Reusable, so there are no sticky sheets to buy', 'Empties into its own self-cleaning base', 'Works on sofas, car seats and bedding', 'No batteries and nothing to wear out'],
      sp: { Brand: 'Meridia', Type: 'Reusable roller', Refills: 'None required', Includes: 'Self-cleaning base' } },
  ],
};
